(() => {
  const en = {
    'Aller au contenu': 'Skip to content', 'PRIVÉ · LOCAL': 'PRIVATE · LOCAL', 'Intelligence de réunion privée': 'Private meeting intelligence', 'DURÉE': 'DURATION',
    'Enregistrer': 'Record', 'Écrire': 'Write', 'Bibliothèque': 'Library', 'Réglages': 'Settings', 'NOUVELLE SESSION': 'NEW SESSION', 'Préparer la réunion': 'Prepare meeting', 'Stockage local': 'Local storage',
    'Sélectionnez une fenêtre ou un écran. Le microphone, l’audio système et la vidéo sont enregistrés séparément sur ce Mac.': 'Choose a window or display. Microphone, system audio, and video are recorded separately on this Mac.',
    'Titre de la réunion': 'Meeting title', 'Réunion sans titre': 'Untitled meeting', 'Langue parlée': 'Spoken language', 'Détection automatique': 'Automatic detection', 'Contexte et vocabulaire': 'Context and vocabulary',
    'Noms, acronymes et termes techniques attendus.': 'Expected names, acronyms, and technical terms.', 'Microphone · vérification…': 'Microphone · checking…', 'Écran et audio système · vérification…': 'Screen and system audio · checking…',
    'Autoriser': 'Allow', 'Vos médias restent sur ce Mac. Seul l’audio à transcrire est envoyé si vous utilisez Synapse Cloud.': 'Your media stays on this Mac. Only audio to transcribe is sent when using Synapse Cloud.', 'Démarrer la réunion': 'Start meeting',
    'Enregistrement en cours': 'Recording', 'Canaux audio': 'Audio channels', 'VOUS · MICROPHONE': 'YOU · MICROPHONE', 'INTERLOCUTEURS · SYSTÈME': 'OTHERS · SYSTEM', 'VOIX RECONNUES': 'RECOGNIZED VOICES', 'Disponibles après analyse': 'Available after analysis',
    'Terminer la réunion': 'End meeting', 'Les fichiers locaux sont finalisés avant la création du compte rendu.': 'Local files are finalized before the summary is created.', 'TRANSCRIPTION DIRECTE': 'LIVE TRANSCRIPT', 'Conversation': 'Conversation', 'DIRECT': 'LIVE',
    'Votre temps de parole': 'Your talk time', 'Mots par minute': 'Words per minute', 'Questions': 'Questions', 'Tour le plus long': 'Longest turn', 'Timeline': 'Timeline', '+ Repère maintenant': '+ Bookmark now', 'Repères de la réunion': 'Meeting bookmarks',
    'En attente de paroles': 'Waiting for speech', 'La transcription apparaîtra ici après quelques secondes.': 'The transcript will appear here after a few seconds.',
    'ÉCRITURE VOCALE': 'VOICE WRITING', 'Parlez librement.': 'Speak freely.', 'Publiez clairement.': 'Publish clearly.', 'Synapse transforme votre dictée en texte fidèle, puis corrige la forme sans modifier les faits.': 'Synapse turns your dictation into faithful text, then improves the writing without changing the facts.',
    'plus rapide que le clavier': 'faster than typing', '01 · INTENTION': '01 · INTENT', 'Préparer le texte': 'Prepare text', 'Prêt': 'Ready', 'Titre': 'Title', 'Nouveau texte vocal': 'New voice document', 'Langue du résultat': 'Output language', 'Même langue': 'Same language',
    'Destination': 'Format', 'Texte': 'Text', 'E-mail': 'Email', 'Article': 'Article', 'Réseaux': 'Social', 'Rapport': 'Report', 'Notes': 'Notes', 'Ton': 'Tone', 'Naturel': 'Natural', 'Professionnel': 'Professional', 'Chaleureux': 'Warm', 'Assuré': 'Confident', 'Concis': 'Concise', 'Persuasif': 'Persuasive',
    'Niveau de réécriture': 'Rewrite level', 'Légère · grammaire seulement': 'Light · grammar only', 'Équilibrée · fluide et fidèle': 'Balanced · fluent and faithful', 'Forte · structure optimisée': 'Strong · optimized structure', 'Apprendre mon style': 'Learn my style', 'Exemple de votre écriture': 'Writing sample',
    'Enregistré localement. Seuls le ton, le rythme et la concision sont imités.': 'Stored locally. Only tone, rhythm, and concision are imitated.', 'Correction au fil de la dictée': 'Correct while dictating', 'Actualise le texte corrigé après chaque passage.': 'Updates the polished text after each passage.', 'Commencer à dicter': 'Start dictating',
    '02 · TEXTE': '02 · TEXT', 'Du brouillon au texte final': 'From raw draft to final text', 'Verbatim': 'Verbatim', 'Texte corrigé': 'Polished text', 'Vos mots, sans modification': 'Your words, unchanged', 'Version corrigée, prête à utiliser': 'Polished version, ready to use', 'mots': 'words', 'min gagnées': 'min saved', 'Langue automatique': 'Automatic language',
    'Corriger avec Synapse': 'Polish with Synapse', 'Copier': 'Copy', 'Exporter': 'Export', 'Nouveau': 'New', 'Deux versions, zéro perte.': 'Two versions, nothing lost.', 'Le verbatim reste intact. Toute correction est réversible et modifiable.': 'The verbatim stays intact. Every edit is reversible and editable.',
    'TEXTES RÉCENTS': 'RECENT TEXTS', 'Reprendre une dictée': 'Resume a dictation', 'Aucun texte pour le moment': 'No documents yet', 'Votre première dictée apparaîtra ici.': 'Your first dictation will appear here.',
    'ARCHIVE LOCALE': 'LOCAL ARCHIVE', 'Réunions et comptes rendus stockés sur ce Mac.': 'Meetings and summaries stored on this Mac.', 'Afficher': 'Show', 'Actives': 'Active', 'Archivées': 'Archived', 'Rechercher…': 'Search…', 'Rechercher dans les réunions': 'Search meetings',
    'Actions rapides': 'Quick actions', 'Favori': 'Favorite', 'Aucun compte rendu.': 'No summary.', 'Aucun résultat': 'No results', 'Essayez un autre mot-clé.': 'Try another keyword.', 'Aucune réunion archivée': 'No archived meetings', 'Les réunions archivées apparaîtront ici.': 'Archived meetings will appear here.', 'Aucune réunion': 'No meetings', 'Démarrez une réunion pour la retrouver ici.': 'Start a meeting to find it here.', 'Effacer la recherche': 'Clear search',
    'TRANSCRIPTION': 'TRANSCRIPTION', 'Reconnaissance vocale': 'Speech recognition', 'Choisissez le moteur utilisé. La langue reste définie pour chaque réunion.': 'Choose the engine to use. Language is set for each meeting.', 'Lieu de traitement': 'Processing location', 'Synapse Cloud': 'Synapse Cloud', 'Modèles Thales administrés': 'Managed Thales models', 'Local · Apple Silicon': 'Local · Apple Silicon', 'Traitement hors ligne sur ce Mac': 'Offline processing on this Mac',
    'Dossier des modèles': 'Models folder', 'Choisir…': 'Choose…', 'Moteur de reconnaissance': 'Recognition engine', 'Enregistrer la transcription': 'Save transcription settings', 'CONNEXION': 'CONNECTION', 'Thales Synapse': 'Thales Synapse', 'La clé API est protégée par le Trousseau macOS. Elle n’est jamais enregistrée dans SQLite ni exportée.': 'The API key is protected by macOS Keychain. It is never stored in SQLite or exported.',
    'Vérification de la connexion…': 'Checking connection…', 'Clé Synapse': 'Synapse key', 'Laissez ce champ vide pour conserver la clé actuelle.': 'Leave empty to keep the current key.', 'Valider et enregistrer': 'Validate and save', 'Tester la clé actuelle': 'Test current key',
    'FINALISATION': 'FINALIZING', 'Enregistrement des médias': 'Saving media', 'Fermeture des fichiers locaux…': 'Closing local files…', 'Progression': 'Progress', 'Vous pouvez laisser cette fenêtre ouverte. Vos fichiers sont déjà conservés localement.': 'Keep this window open. Your files are already stored locally.',
    'Confirmer': 'Confirm', 'Sauvegarder': 'Save', 'Annuler': 'Cancel', 'Fermer': 'Close', 'Langue de l’interface': 'Interface language', 'Français': 'French', 'Anglais': 'English', 'Allemand': 'German', 'Espagnol': 'Spanish', 'Italien': 'Italian', 'Portugais': 'Portuguese', 'Néerlandais': 'Dutch', 'Polonais': 'Polish', 'Ukrainien': 'Ukrainian', 'Japonais': 'Japanese', 'Chinois': 'Chinese', 'Coréen': 'Korean', 'Arabe': 'Arabic', 'Hindi': 'Hindi', 'Turc': 'Turkish', 'Russe': 'Russian', 'Suédois': 'Swedish', 'Danois': 'Danish', 'Norvégien': 'Norwegian', 'Finnois': 'Finnish', 'Tchèque': 'Czech', 'Roumain': 'Romanian', 'Hongrois': 'Hungarian', 'Grec': 'Greek', 'Hébreu': 'Hebrew', 'Indonésien': 'Indonesian', 'Vietnamien': 'Vietnamese', 'Thaï': 'Thai', 'Bulgare': 'Bulgarian', 'Croate': 'Croatian', 'Slovaque': 'Slovak',
    'Modifier': 'Edit', 'Archiver': 'Archive', 'Restaurer': 'Restore', 'Supprimer': 'Delete', 'Ajouter aux favoris': 'Add to favorites', 'Retirer des favoris': 'Remove from favorites', 'Retranscrire': 'Retranscribe', 'Fichiers': 'Files', 'Compte rendu': 'Summary', 'Points clés': 'Key points', 'Actions': 'Actions', 'Transcription': 'Transcript', 'Repères': 'Bookmarks', 'Voix reconnues': 'Recognized voices', 'Aucune voix séparée': 'No separated voices', 'Enregistrer les notes': 'Save notes',
    'Modifier la réunion': 'Edit meeting', 'Changez son titre.': 'Change its title.', 'Sauvegarder': 'Save', 'Supprimer cette réunion ?': 'Delete this meeting?', 'La transcription et tous les enregistrements locaux seront supprimés définitivement.': 'The transcript and all local recordings will be permanently deleted.', 'Supprimer définitivement': 'Delete permanently',
    'Créer un nouveau texte ?': 'Create a new document?', 'La dictée actuelle reste enregistrée dans les textes récents.': 'The current dictation remains saved in recent documents.', 'Créer un texte': 'Create document', 'Supprimer ce texte ?': 'Delete this document?', 'Le texte et son enregistrement audio local seront supprimés définitivement.': 'The text and its local audio recording will be permanently deleted.',
    'À l’écoute': 'Listening', 'Transcription…': 'Transcribing…', 'Correction…': 'Polishing…', 'Finalisation…': 'Finalizing…', 'Brouillon prêt': 'Draft ready', 'Brouillon conservé': 'Draft saved', 'Texte corrigé': 'Polished text', 'Arrêter la dictée': 'Stop dictating',
    'Aucun texte à copier': 'No text to copy', 'Enregistrez d’abord une dictée': 'Save a dictation first', 'Texte copié': 'Text copied', 'Texte exporté': 'Text exported', 'Texte supprimé': 'Text deleted', 'Titre modifié': 'Title updated', 'Réunion archivée': 'Meeting archived', 'Réunion restaurée': 'Meeting restored', 'Réunion supprimée': 'Meeting deleted', 'Réunion démarrée': 'Meeting started', 'Réunion sauvegardée': 'Meeting saved',
    'Ajouté aux favoris': 'Added to favorites', 'Retiré des favoris': 'Removed from favorites', 'Notes enregistrées': 'Notes saved', 'Repère ajouté à la timeline': 'Bookmark added to timeline', 'Repère supprimé': 'Bookmark deleted', 'Export Markdown créé': 'Markdown export created', 'Transcription terminée': 'Transcription complete', 'Modèle téléchargé': 'Model downloaded', 'Dossier des modèles mis à jour': 'Models folder updated', 'Réglages de transcription enregistrés': 'Transcription settings saved', 'Clé Synapse enregistrée': 'Synapse key saved', 'Connexion Synapse réussie': 'Synapse connection successful',
    'Préparation…': 'Preparing…', 'Téléchargement…': 'Downloading…', 'Validation…': 'Validating…', 'Enregistrement…': 'Saving…', 'Transcription…': 'Transcribing…', 'Test…': 'Testing…', 'Ouverture…': 'Opening…',
    'Ajoutez un titre à la réunion.': 'Add a meeting title.', 'Ajoutez une note courte à ce point de la timeline.': 'Add a short note at this point in the timeline.', 'Note facultative': 'Optional note', 'Ajouter': 'Add', 'Repère': 'Bookmark', 'Moment important': 'Important moment',
    'Changez son titre. La transcription et les fichiers restent inchangés.': 'Change its title. The transcript and files stay unchanged.', 'La transcription, les notes et tous les enregistrements locaux seront supprimés définitivement.': 'The transcript, notes, and all local recordings will be permanently deleted.', 'Le nouveau nom sera appliqué à toutes ses interventions.': 'The new name will be applied to all their contributions.', 'Renommer cette voix': 'Rename this voice', 'Nom': 'Name', 'Renommer': 'Rename',
    'Relancer la transcription': 'Run transcription again', 'Utilisez « auto » ou un code de langue, par exemple fr ou en.': 'Use “auto” or a language code such as fr or en.', 'Relancer': 'Run again', 'Langue': 'Language', 'Ouvrir les fichiers': 'Open files',
    'Votre débit est élevé. Ralentissez légèrement pour gagner en clarté.': 'You are speaking quickly. Slow down slightly for clarity.', 'Votre dernier tour de parole est long. Faites une pause pour vérifier la compréhension.': 'Your latest turn is long. Pause to check understanding.', 'Vous occupez la majorité du temps de parole. Invitez votre interlocuteur à répondre.': 'You are taking most of the talk time. Invite the other person to respond.',
    'Aucune transcription': 'No transcript', 'Relancez la transcription à partir des fichiers audio conservés.': 'Run transcription again from the saved audio files.', 'Aucun compte rendu disponible. Relancez la transcription pour réessayer.': 'No summary available. Run transcription again to retry.', 'Aucun point clé détecté.': 'No key points detected.', 'Aucune action détectée.': 'No action items detected.', 'Aucun repère.': 'No bookmarks.', 'Dictée vide': 'Empty dictation', 'Corrigé': 'Polished',
    'Chargement des réunions': 'Loading meetings', 'Chargement des modèles': 'Loading models', 'Aucun modèle disponible': 'No models available', 'Transcription audio': 'Audio transcription', 'Testez la connexion Synapse puis réessayez.': 'Test the Synapse connection and try again.',
    'Terminer avant de quitter ?': 'Finish before quitting?', 'La dictée doit être finalisée pour conserver les dernières paroles.': 'The dictation must be finalized to save the latest words.', 'La réunion doit être finalisée pour conserver la vidéo et les dernières paroles.': 'The meeting must be finalized to save the video and latest words.', 'Terminer et quitter': 'Finish and quit',
    'Le partage d’écran est terminé. Finalisation de la réunion…': 'Screen sharing ended. Finalizing the meeting…', 'Écran et audio système': 'Screen and system audio', 'Microphone': 'Microphone', 'requis': 'required', 'autorisé': 'allowed', 'actif': 'active', 'calme': 'quiet',
  };
  const patterns = [
    [/^Modifier (.+)$/, 'Edit $1'], [/^Archiver (.+)$/, 'Archive $1'], [/^Restaurer (.+)$/, 'Restore $1'], [/^Supprimer (.+)$/, 'Delete $1'], [/^Ouvrir (.+)$/, 'Open $1'],
    [/^Langue détectée · (.+)$/, 'Detected language · $1'], [/^(.+) segments$/, '$1 segments'], [/^(.+) segment$/, '$1 segment'], [/^Durée inconnue$/, 'Unknown duration'],
  ];
  const fr = Object.fromEntries(Object.entries(en).map(([source, target]) => [target, source]));
  let language = localStorage.getItem('ui-language') === 'en' ? 'en' : 'fr';
  const sources = new WeakMap(), attributeSources = new WeakMap();
  function translated(value) {
    const dictionary = language === 'en' ? en : fr;
    if (dictionary[value]) return dictionary[value];
    if (language === 'en') for (const [pattern, replacement] of patterns) if (pattern.test(value)) return value.replace(pattern, replacement);
    return value;
  }
  function apply(root = document.body) {
    if (!root) return;
    const walker = document.createTreeWalker(root, NodeFilter.SHOW_TEXT);
    for (let node = walker.nextNode(); node; node = walker.nextNode()) {
      if (!node.nodeValue.trim() || ['SCRIPT', 'STYLE'].includes(node.parentElement?.tagName) || node.parentElement?.closest('.detail-transcript, .summary-box p, .summary-box li, .meeting-head strong, .meeting-main p, .writing-card strong, .writing-card p, #detailTitle')) continue;
      if (!sources.has(node)) sources.set(node, node.nodeValue);
      const source = sources.get(node), leading = source.match(/^\s*/)[0], trailing = source.match(/\s*$/)[0];
      node.nodeValue = leading + translated(source.trim()) + trailing;
    }
    const elements = [root, ...(root.querySelectorAll ? root.querySelectorAll('*') : [])];
    for (const element of elements) for (const attribute of ['placeholder', 'title', 'aria-label']) if (element?.hasAttribute?.(attribute)) {
      let values = attributeSources.get(element); if (!values) { values = {}; attributeSources.set(element, values); }
      values[attribute] ??= element.getAttribute(attribute); element.setAttribute(attribute, translated(values[attribute]));
    }
    document.documentElement.lang = language;
    document.querySelectorAll('[data-ui-language]').forEach(button => { const active = button.dataset.uiLanguage === language; button.classList.toggle('active', active); button.setAttribute('aria-pressed', active); });
  }
  function setLanguage(next) { language = next === 'en' ? 'en' : 'fr'; localStorage.setItem('ui-language', language); apply(); window.dispatchEvent(new CustomEvent('app-language', { detail: language })); }
  new MutationObserver(records => records.forEach(record => record.addedNodes.forEach(node => { if (node.nodeType === Node.ELEMENT_NODE) apply(node); else if (node.nodeType === Node.TEXT_NODE && node.parentElement) apply(node.parentElement); }))).observe(document.documentElement, { childList: true, subtree: true });
  window.i18n = { apply, setLanguage, get language() { return language; }, locale() { return language === 'en' ? 'en-US' : 'fr-FR'; } };
  apply();
})();
